### ISSUE TITLE
OUTI: Koha-Ceepos-maksurajapinta antaa virheilmoituksen "Error: ERROR 98: System error" yhdelle asiakkaalle

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/koha-plugin-ceepos-integration#2]
### Mikä vikana?

Kun yrittää lähettää asiakkaan borrowernumber=65462 maksuja Kohasta Ceeposiin, Koha antaa virheilmoituksen: 
![image](https://github.com/KohaSuomi/Koha/assets/98814860/68b72b83-5503-48d6-9ab7-98a4bfc20e91)
Ilmoitus tulee sen jälkeen, kun Kohassa on valittu asiakkaan Maksa maksuja -sivulla "Ceepos-maksu" ja virkailija on kuitannut OK:lla Kohan antaman ilmoituksen "Maksu lähetetty, käsittele kassassa!"

Ongelmatilanne oli tullut vastaan ensimmäisen kerran 3.8. n. klo 13.54 , kun virkailija (301947) oli ensin poistanut asiakkaalta vanhentuneita maksuja Kohan toiminnolla "Poista valitut" ja tämän jälkeen yrittänyt lähettää jäljelle jääneitä maksuja Kohasta Ceeposiin. 

Ongelma ei ole ollut hetkellinen häiriö, koska asiakkaan maksuja ei pysty vieläkään lähettämään Ceeposiin.  Sama virheilmoitus tulee, jos yrittää lähettää maksuja myös eri kirjastossa eri kassalle.

Testasin myös itse vastaavaa tapausta, että poistin ensin maksuja, jonka jälkeen lähetin loput maksut Ceeposiin. Ei tullut vastaavaa ongelmatilannetta. Myös muiden asiakkaiden maksujen lähetykset ja maksukuittaukset toimivat ongelmitta.

**Comment by emta001** [comment]
Tästä kannattanee kysäistä ihan Ceepokselta, tuo virheilmoitus käsittääkseni voisi viitata ongelmaan siellä päässä. Ainakaan meidän päästä ei vaikuttaisi äkkiseltään löytyvän tälle mitään järjellistä selitystä. Jos Ceepoksenkin päässä homma on OK, niin jatketaan sitten meidän päässä tutkimista.

**Comment by pirliis** [comment]
Voinhan kysyä CPU:lta, näkevätkö mitään ko. ajankohtana Ceeposin lokilta. Tosin Koha-Ceepos maksurajapinta toimii kaikkien muiden asiakkaiden kohdalla ongelmitta. Myös kassalla, jossa tämä ongelma oli tullut ilmi tämän asiakkaan kohdalla, heti seuraavan asiakkaan maksujen lähetyksessä ei kuulemma ollut mitään ongelmaa.

**Comment by emta001** [comment]
> Voinhan kysyä CPU:lta, näkevätkö mitään ko. ajankohtana Ceeposin lokilta. Tosin Koha-Ceepos maksurajapinta toimii kaikkien muiden asiakkaiden kohdalla ongelmitta. Myös kassalla, jossa tämä ongelma oli tullut ilmi tämän asiakkaan kohdalla, heti seuraavan asiakkaan maksujen lähetyksessä ei kuulemma ollut mitään ongelmaa.

No sehän tässä hämmentääkin, miksi vain tällä asiakkaalla ei mene maksu läpi :D Näemmä maksua on yritetty myös 4.8., niistä oli tullut samat virheet. Mutta tosiaan vaikea sanoa mitä tässä tapahtuu, kun lokeihinkaan ei tule mitään.

**Comment by pirliis** [comment]
CPU on tutkinut ongelmaa. Kävi ilmi, että kun lähetettävistä maksuista jätti pois maksun, jonka kuvaus (teoksen nimi) on pitkä (Kuusamon Veteläiset, Tuovilat, Majavat, Pulkkaset...), maksun lähetys Ceeposiin toimi ongelmitta.

CPU:n kommentti: _"Tuotteen kuvauksen maksimipituus on tosiaan 100 merkkiä ja tuon tuotteen kohalla se katkeaa. Katkaisussa ei sinänsä pitäisi olla mitään ongelmaa, mutta tämä vaikuttaa nyt liittyvän merkistöön jollain tapaa." 
Olisiko tuosta virheen aiheuttavasta maksusta mahdollista saada kohan lähettämää alkuperäistä json-sanomaa
kokonaisuudessaan?"_

Jos sanoma on mahdollista laittaa tähän tikettiin, voisin kopsata sen s-postiviestiketjuun, jota olen käynyt CPU:n kanssa.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 21.8.2023: Ceepos ei suostu lokittamaan mitään, joten json-sanomaa ei tällä hetkellä saada. Yritetään saada lokitus toimimaan.

**Comment by pirliis** [comment]
> Koha-Suomen palaveri 21.8.2023: Ceepos ei suostu lokittamaan mitään, joten json-sanomaa ei tällä hetkellä saada. Yritetään saada lokitus toimimaan.

Millä aikataululla? :)

**Comment by emta001** [comment]
> > Koha-Suomen palaveri 21.8.2023: Ceepos ei suostu lokittamaan mitään, joten json-sanomaa ei tällä hetkellä saada. Yritetään saada lokitus toimimaan.
> 
> Millä aikataululla? :)

Vaikea sanoa, koska ongelman syy ei ole selvillä. Mutta selvittely on työn alla parhaillaan, päivittelen aikataulua kunhan jotain selviää.

**Comment by lmstrand** [comment]
Lokitus on korjattu ja on testattu outin testillä (saattanut mennä pari kymmenen sentin maksua testauskäytössä olleeseen kassaan). Viedään päivitys tuotantoon tiistaina.

**Comment by pirliis** [comment]
> Lokitus on korjattu ja on testattu outin testillä (saattanut mennä pari kymmenen sentin maksua testauskäytössä olleeseen kassaan). Viedään päivitys tuotantoon tiistaina.

Hyvä homma. Tehdään ensi viikolla testimaksu tuotannossa, niin näette millaista lokia saatte.
Kävin tarkistamassa kassalla, ylimääräisiä maksuja ei ollut siirtynyt.

**Comment by pirliis** [comment]
Asiakkaan borrowernumber=65462 ongelmamaksujen lähetystä kassalle 15 on taas testattu 29.8.2023 n. klo 12.09. Saatteko json-sanomaa CPU:lle?

**Comment by emta001** [comment]
Loki toimitettu Elementsissä.

**Comment by pirliis** [comment]
Onkohan tähän saatu jo korjausta/selvitystä? Tämä jäi siihen vaiheeseen, että välitin CPU:lta tulleen kysymysviestin support-postiin 30.8., kun kysymykset alkoivat olla niin teknisiä. :)

Aattelin, että voisimmeko asiakkaan ongelmamaksun hoitaa häneltä jo pois?

**Comment by emta001** [comment]
> Onkohan tähän saatu jo korjausta/selvitystä? Tämä jäi siihen vaiheeseen, että välitin CPU:lta tulleen kysymysviestin support-postiin 30.8., kun kysymykset alkoivat olla niin teknisiä. :)
> 
> Aattelin, että voisimmeko asiakkaan ongelmamaksun hoitaa häneltä jo pois?

Minulta on mennyt jostain syystä täysin ohi tuo sposti (EDIT. vaikka oon näemmä ite pyytänyt sen tuonne välittämään). Pahoittelut, vilasen sitä kunhan ehdin.

**Comment by emta001** [comment]
Elikäs syy saattoi nyt viimein selvitä (kun tarpeeksi ajatuksen kanssa tuota CPU:n viestiä ja meidän koodia tuijotti). Niteen nimeke siis muunnetaan ensin utf8 muotoon, jolloin sinne tulee noita hassuja merkkejä. Tämän jälkeen nimeke pätkäistään lyhyemmäksi ja tämän kyseisen nimekkeen kohdalla tuon viimeisenä olevan merkin perästä jää uupumaan ¤.

Lari ehdotti, että pätkäisy tehtäisiin vasta sitten kun nimekeessä tulee vastaan ensimmäinen välilyönti sallitun pituuden täyttyessä. Mutta ensin on kysyttävä CPU:lta onnistuuko tämä vai onko sille jokin syy miksi nimeke katkotaan. Laittelen heille viestiä maanantaina ja katsotaan sitten mitä asialla voidaan tehdä.

**Comment by emta001** [comment]
> Elikäs syy saattoi nyt viimein selvitä (kun tarpeeksi ajatuksen kanssa tuota CPU:n viestiä ja meidän koodia tuijotti). Niteen nimeke siis muunnetaan ensin utf8 muotoon, jolloin sinne tulee noita hassuja merkkejä. Tämän jälkeen nimeke pätkäistään lyhyemmäksi ja tämän kyseisen nimekkeen kohdalla tuon viimeisenä olevan merkin perästä jää uupumaan ¤.
> 
> Lari ehdotti, että pätkäisy tehtäisiin vasta sitten kun nimekeessä tulee vastaan ensimmäinen välilyönti sallitun pituuden täyttyessä. Mutta ensin on kysyttävä CPU:lta onnistuuko tämä vai onko sille jokin syy miksi nimeke katkotaan. Laittelen heille viestiä maanantaina ja katsotaan sitten mitä asialla voidaan tehdä.

Korjaus tähän, Larin ehdotti pätkäisyä "viimeiseen välilyöntiin jos merkkijonon pituus on liian pitkä". Eli juuri toisinepäin. Tämän luulisi onnistuvan ja kelpaavan myös CPU:lle, koska tässä ei ylitetä 100 merkin ylärajaa.

**Comment by pirliis** [comment]
Korjausehdotus on oletettavasti kelvannut CPU:lle, koska ovat sulkeneet tiketin heidän päässä. 
Ilmoitelkaa, kun ehdottamanne muutoskorjaus on tehty, niin testaan taas. :)

**Comment by emta001** [comment]
Siirrän tän tiketin Ceepos-plugarin repon alle.

**Comment by emta001** [comment]
Korjaus testattu testeillä ja viety tuotantoon. Asiakkaan maksut saatiin onnistuneesti maksettua.

**Comment by pirliis** [comment]
Tämä ongelma on saatu ratkaistua, kiitos!  Suljen tiketin.
