### ISSUE TITLE
Ceepos-napin siirtäminen pois intranetuserjs-asetuksesta.

### ISSUE THREAD

**Issue by johannaraisa** [KohaSuomi/koha-plugin-ceepos-integration#6]
Jotta pystymme seuraamaan mitä muutoksia ceepoksen-nappiin tehdään, siirretään sen toiminnallisuus (js-rimpsut) liitännäiseen. Nappi näkyy kaikille kirjastopisteille jotka ovat määritelty liitännäisen asetuksessa.

**Comment by johannaraisa** [comment]
Tämä on tehty OUTIn testille, testauksessa voi käydä lisäämässä asetukseen haluamansa kirjastopisteen ja katsoa ilmestyykö nappi maksusivulle.

**Comment by johannaraisa** [comment]
Tämä on laitettu nyt myös Vaaran ja Lapin testeihin niille kunnille joilla se on tuotannossa.

**Comment by pirliis** [comment]
> Tämä on tehty OUTIn testille, testauksessa voi käydä lisäämässä asetukseen haluamansa kirjastopisteen ja katsoa ilmestyykö nappi maksusivulle.

Ceeposmaksu-painike tuli kaikille OUTIn kirjastoille, joille lisäsin kassanumeron.

Testille oli ilmaantunut Maksa kaikki -painike, jota ei tuotannossa ole.
![image](https://github.com/KohaSuomi/koha-plugin-ceepos-integration/assets/98814860/0774a00e-85f3-4888-bc83-ea1aaa689fca)

**Comment by johannaraisa** [comment]
> > Tämä on tehty OUTIn testille, testauksessa voi käydä lisäämässä asetukseen haluamansa kirjastopisteen ja katsoa ilmestyykö nappi maksusivulle.
> 
> Ceeposmaksu-painike tuli kaikille OUTIn kirjastoille, joille lisäsin kassanumeron.
> 
> Testille oli ilmaantunut Maksa kaikki -painike, jota ei tuotannossa ole. ![image](https://private-user-images.githubusercontent.com/98814860/309773846-0774a00e-85f3-4888-bc83-ea1aaa689fca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTM3ODgsIm5iZiI6MTcwOTc5MzQ4OCwicGF0aCI6Ii85ODgxNDg2MC8zMDk3NzM4NDYtMDc3NGEwMGUtODVmMy00ODg4LWJjODMtZWExYWFhNjg5ZmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2MzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ODZhYmU0MzhhNTBkZjU0NWEyMzQ0ODc1ZDdkNTEzZGQwZjMyNDg4M2Y5MzU5OTY0ZmEzN2MzNDRjNzVmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K9zsk4ncj3YB4bsEK-l0czSlIImvZldfyGRRWJneT6A)

Hyvä havainto, piilotetaanpas tuo myös.

**Comment by pirliis** [comment]
Tuotannossa meillä on tuolla samaisessa asetuskohdassa Kohan ja Ceeposin tuotemäppäykset. Tuleeko mäppäykset jatkossa tuohon samaan asetusnäkymään?

**Comment by johannaraisa** [comment]
> Tuotannossa meillä on tuolla samaisessa asetuskohdassa Kohan ja Ceeposin tuotemäppäykset. Tuleeko mäppäykset jatkossa tuohon samaan asetusnäkymään?

Joo, se säilyy ennallaan. OUTIn testillä ei vain ollut niitä tuotannon mäppäyksiä ja en jaksanut käydä kopioimassa. Samaisesta asetuksesta otetaan jatkossa ne kirjastopisteet joille nappi näytetään, ni ei tarvitse säädellä javascriptissä.

**Comment by pirliis** [comment]
> > Tuotannossa meillä on tuolla samaisessa asetuskohdassa Kohan ja Ceeposin tuotemäppäykset. Tuleeko mäppäykset jatkossa tuohon samaan asetusnäkymään?
> 
> Joo, se säilyy ennallaan. OUTIn testillä ei vain ollut niitä tuotannon mäppäyksiä ja en jaksanut käydä kopioimassa. Samaisesta asetuksesta otetaan jatkossa ne kirjastopisteet joille nappi näytetään, ni ei tarvitse säädellä javascriptissä.

Okei. Tallensin tuotemäppäykset nyt myös testille Ceepos-nappi määrityksien perään. Mäppäykset toimivat ilmeisesti mitään sen kummempaa?

**Comment by johannaraisa** [comment]
> > > Tuotannossa meillä on tuolla samaisessa asetuskohdassa Kohan ja Ceeposin tuotemäppäykset. Tuleeko mäppäykset jatkossa tuohon samaan asetusnäkymään?
> > 
> > 
> > Joo, se säilyy ennallaan. OUTIn testillä ei vain ollut niitä tuotannon mäppäyksiä ja en jaksanut käydä kopioimassa. Samaisesta asetuksesta otetaan jatkossa ne kirjastopisteet joille nappi näytetään, ni ei tarvitse säädellä javascriptissä.
> 
> Okei. Tallensin tuotemäppäykset nyt myös testille Ceepos-nappi määrityksien perään. Mäppäykset toimivat ilmeisesti mitään sen kummempaa?

Joo, pitäisi toimia samalla tavalla kuin ennenkin.

**Comment by johannaraisa** [comment]
Nyt on piilotettu nappi, oli näköjään jäänyt väärälle puolelle if-lausetta.

**Comment by pirliis** [comment]
> Nyt on piilotettu nappi, oli näköjään jäänyt väärälle puolelle if-lausetta.

Kyllä nappi näyttäisi tulevan vielä testillä kuin myös nextillä.

**Comment by johannaraisa** [comment]
> > Nyt on piilotettu nappi, oli näköjään jäänyt väärälle puolelle if-lausetta.
> 
> Kyllä nappi näyttäisi tulevan vielä testillä kuin myös nextillä.

Taikakomento käyttöön, ctrl+f5. Minulla ei ainakaan enää näy kummassakaan.

**Comment by pirliis** [comment]
> > > Nyt on piilotettu nappi, oli näköjään jäänyt väärälle puolelle if-lausetta.
> > 
> > 
> > Kyllä nappi näyttäisi tulevan vielä testillä kuin myös nextillä.
> 
> Taikakomento käyttöön, ctrl+f5. Minulla ei ainakaan enää näy kummassakaan.

Taikakomento auttoi. :D Kiitos!

**Comment by pknuuti** [comment]
Vaaran testillä näkyy kolme nappia.

![Image](https://github.com/KohaSuomi/koha-plugin-ceepos-integration/assets/73887264/507d859a-2a73-4145-8299-3145ab54c22a)

**Comment by AnneliO** [comment]
Päivittäjä: IntranetUserJS:stä pitää ottaa pois vanha rimpsu.

**Comment by johannaraisa** [comment]
Päivittää 22.xx branchin ja ajaa install_plugins.pl:n

**Comment by AnneliO** [comment]
Joko tämän tiketin saa sulkea? :)

**Comment by johannaraisa** [comment]
Suljetaan.
